Repository Feeda-Project/spring-feeda, pull requests merged in 2025-06, with the labels that each got.

#35 [#32] 팔로우 페이지네이션으로 변경
  src/main/java/com/example/feeda/domain/follow/controller/FollowsController.java
  src/main/java/com/example/feeda/domain/follow/repository/FollowsRepository.java
  src/main/java/com/example/feeda/domain/follow/service/FollowsService.java
  src/main/java/com/example/feeda/domain/follow/service/FollowsServiceImpl.java
Labels: 🚀 feature

#36 [#31] 댓글 CRUD 기능 구현 및 권한 검증 추가
  src/main/java/com/example/feeda/domain/comment/controller/CommentController.java
  src/main/java/com/example/feeda/domain/comment/dto/CommentResponse.java
  src/main/java/com/example/feeda/domain/comment/dto/CreateCommentRequest.java
  src/main/java/com/example/feeda/domain/comment/dto/UpdateCommentRequest.java
  src/main/java/com/example/feeda/domain/comment/entity/Comment.java
  src/main/java/com/example/feeda/domain/comment/service/CommentService.java
Labels: 🚀 feature

#38 [#37] 팔로우 기능 테스트 코드 작성
  build.gradle
  src/test/java/com/example/feeda/unit/service/FollowServiceTest.java
  src/test/resources/application-test.yml
Labels: 🚀 feature

#40 [#39] 폴더 구조 정리
  src/main/java/com/example/feeda/domain/account/controller/AccountController.java
  src/main/java/com/example/feeda/domain/account/repository/AccountRepository.java
  src/main/java/com/example/feeda/domain/account/sevice/AccountService.java
  src/main/java/com/example/feeda/domain/post/.gitkeep
Labels: 🛠 refactor

#51 게시글 좋아요 추가/제거
  src/main/java/com/example/feeda/domain/post/controller/PostController.java
  src/main/java/com/example/feeda/domain/post/dto/PostLikeResponseDTO.java
  src/main/java/com/example/feeda/domain/post/dto/PostResponseDto.java
  src/main/java/com/example/feeda/domain/post/entity/Post.java
  src/main/java/com/example/feeda/domain/post/repository/PostLikeRepository.java
  src/main/java/com/example/feeda/domain/post/service/PostService.java
  src/main/java/com/example/feeda/domain/post/service/PostServiceImpl.java
Labels: 🚀 feature

#52 [#49] 게시글 기간 조회
  src/main/java/com/example/feeda/domain/comment/repository/CommentRepository.java
  src/main/java/com/example/feeda/domain/post/controller/PostController.java
  src/main/java/com/example/feeda/domain/post/dto/PostResponseDto.java
  src/main/java/com/example/feeda/domain/post/repository/PostRepository.java
  src/main/java/com/example/feeda/domain/post/service/PostService.java
  src/main/java/com/example/feeda/domain/post/service/PostServiceImpl.java
Labels: 🚀 feature

#54 [#53] 예외 처리 기능 구현
  src/main/java/com/example/feeda/config/SecurityConfig.java
  src/main/java/com/example/feeda/domain/account/controller/AccountController.java
  src/main/java/com/example/feeda/domain/account/sevice/AccountService.java
  src/main/java/com/example/feeda/domain/account/sevice/AccountServiceImpl.java
  src/main/java/com/example/feeda/domain/comment/service/CommentLikeService.java
  src/main/java/com/example/feeda/domain/comment/service/CommentService.java
  src/main/java/com/example/feeda/domain/follow/service/FollowsServiceImpl.java
  src/main/java/com/example/feeda/domain/post/controller/PostController.java
  src/main/java/com/example/feeda/domain/post/dto/PostResponseDto.java
  src/main/java/com/example/feeda/domain/post/entity/Post.java
  src/main/java/com/example/feeda/domain/post/service/PostServiceImpl.java
  src/main/java/com/example/feeda/domain/profile/controller/ProfileController.java
  src/main/java/com/example/feeda/domain/profile/service/ProfileService.java
  src/main/java/com/example/feeda/domain/profile/service/ProfileServiceImpl.java
  src/main/java/com/example/feeda/exception/CustomResponseException.java
  src/main/java/com/example/feeda/exception/GlobalExceptionHandler.java
  src/main/java/com/example/feeda/exception/JwtValidationException.java
  src/main/java/com/example/feeda/exception/enums/ResponseError.java
  src/main/java/com/example/feeda/exception/enums/ServletResponseError.java
  src/main/java/com/example/feeda/filter/JwtFilter.java
  src/main/java/com/example/feeda/security/handler/CustomAccessDeniedHandler.java
  src/main/java/com/example/feeda/security/handler/CustomAuthenticationEntryPoint.java
  src/main/java/com/example/feeda/security/jwt/JwtUtil.java
Labels: 🚀 feature

#55 [#53] 전역 예외처리기 오류 해결
  src/main/java/com/example/feeda/exception/GlobalExceptionHandler.java
Labels: 🐞 bug
